### ISSUE TITLE
Utility for entering a container

### ISSUE THREAD

**Issue by glyn** [docker/libcontainer#183]
A utility for entering a container and poking around to debug problems is required. This should be documented and supported as a libcontainer deliverable.

If possible, the utility should be implemented on top of the API and would then serve as a sample program.

Cloud Foundry would like this issue to be fixed.

**Comment by xiaods** [comment]
I think this issue can close.

**Comment by crosbymichael** [comment]
@xiaods 

Thanks!

I think this can be closed now as we have docker exec and nsinit has more information on the cli
