### ISSUE TITLE
SocketGroup is ignored if not in /etc/group even if gid specified

### ISSUE THREAD

**Issue by grossws** [docker/libcontainer#232]
I use centralized group management in system (so _nss_ resolves groups through some backend other than `files`) and docker can't find group (even if gid specified), so socket is owned by `root.root` instead of gid in `SocketGroup=<some-gid>`.

I think, docker should resolve groups via standard mechanism (not by parsing `/etc/groups`). To get group `getent group <group-name>` can be used (from glibc-common).

Maybe user management should be done using `getent passwd <user-name>`

See: https://github.com/docker/libcontainer/blob/master/user/user.go#L124.

**Comment by LK4D4** [comment]
Whole idea of that package was to break dependency on libc. I think Getuser from stdlib calls that function. Probably later we will inroduce static linking, but for now we prefer to keep all programs statically linked.

**Comment by grossws** [comment]
It's not a problem now since `docker -d -G gid` works fine on 1.6.
