### ISSUE TITLE
Problems Creating / Bringing up Bridge

### ISSUE THREAD

**Issue by jason-riddle** [docker/libcontainer#270]
#### Stats

```bash
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

# uname -a 
Linux UbuntuVM 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# go version
go version go1.3.3 linux/amd64
```

#### Problem
After running the following command <code>sudo -E go run libcontainer-br.go</code> where <code>libcontainer-br.go</code> contains ..
```go
// libcontainer-br.go
package main

import (
    "fmt"
    "github.com/docker/libcontainer/netlink"
)

func main() {
    if err := netlink.CreateBridge("libcontainer-br", true); err != nil {
        fmt.Println(err)
    }
}
```

.. creates the following link.
```bash
# ip addr show dev libcontainer-br
5: libcontainer-br: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
```

However, I am unable to bring up this link with <code>sudo ip link set libcontainer-br up</code> but, instead the interface remains down.
```bash
# ip addr show dev libcontainer-br
5: libcontainer-br: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
```
#### What's Expected
What I am expecting is that when I run <code>sudo ip link add dev cmd-br type bridge</code> in the command line and inspect the interface..
```bash
# ip addr show dev cmd-br
6: cmd-br: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 4a:6e:ed:c3:87:b5 brd ff:ff:ff:ff:ff:ff
```

I am successfully able to bring the interface up? (or to an UNKNOWN state) with <code>sudo ip link set cmd-br up</code> where the interface now looks like..
```bash
# ip addr show dev cmd-br
6: cmd-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 4a:6e:ed:c3:87:b5 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::486e:edff:fec3:87b5/64 scope link 
       valid_lft forever preferred_lft forever
```

I've also noticed that after `cmd-br` and `libcontainer-br` are brought up, then `cmd-br` has the following flags <code>BROADCAST,MULTICAST,UP,LOWER_UP</code> while `libcontainer-br` flags are <code>NO-CARRIER,BROADCAST,MULTICAST,UP</code>.

**Comment by LK4D4** [comment]
@jason-riddle use vishvananda/netlink library for netlink calls. It is pretty well supported now.
