### ISSUE TITLE
Unable to build libcontainer

### ISSUE THREAD

**Issue by bcornec** [docker/libcontainer#272]
Hello,

This is probably a dummy issue, so bare with me. Sorry to create a BR for that, but couldn't find anything on this topic after hours of tries, so thought I would ask here:

I'm trying to package libcontainer (and docker) for Mageia. We had the previous 1.1.0 version working. In order to support docker 1.3.1, I updated libcontainer to 1.2.0.

But his one doesn't build:

+ mkdir -p ./_build/src/github.com/docker
++ pwd
+ ln -s /users/bruno/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0 ./_build/src/github.com/docker/libcontainer
++ pwd
+ export GOPATH=/users/bruno/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0/_build:/usr/lib64/golang
+ GOPATH=/users/bruno/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0/_build:/usr/lib64/golang
++ pwd
+ pushd /users/bruno/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0/_build/src
~/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0/_build/src ~/prj/mageia/golang-libcontainer/BUILD/libcontainer-1.2.0
+ go build github.com/docker/libcontainer/nsinit
# github.com/docker/libcontainer/namespaces/nsenter
/tmp/go-build681149517/github.com/docker/libcontainer/namespaces/nsenter/_obj/nsenter.cgo2.o: dans la fonction « init »:
/usr/lib64/golang/src/pkg/github.com/docker/libcontainer/namespaces/nsenter/nsenter.go:7: référence indéfinie vers « nsenter »
collect2: erreur: ld a retourné 1 code d'état d'exécution
erreur : Mauvais statut de sortie pour /users/bruno/prj/mageia/golang-libcontainer/BUILDROOT/rpm-tmp.8GL0hS (%build)

I also tried with the latest git version from the master branch, without more luck:
mkdir -p ./_build/src/github.com/docker
ln -s $(pwd) ./_build/src/github.com/docker/libcontainer
export GOPATH=$(pwd)/_build:/usr/lib64/golang
cd _build/src/
go build github.com/docker/libcontainer/nsinit
# github.com/docker/libcontainer/namespaces/nsenter
/tmp/go-build423050216/github.com/docker/libcontainer/namespaces/nsenter/_obj/nsenter.cgo2.o: dans la fonction « init »:
/usr/lib64/golang/src/pkg/github.com/docker/libcontainer/namespaces/nsenter/nsenter.go:7: référence indéfinie vers « nsenter »
collect2: erreur: ld a retourné 1 code d'état d'exécution

I'm sure I'm missing something obvious, but as I'm not a Go expert, more of a dummy, I cannot help myself sorry.

Any hint ?
Any link to any doc on building these components ?

**Comment by xiaods** [comment]
@bcornec because you use a Mageia distribution. Do you have selinux settings? if have it, please disable it. then rebuild again.

**Comment by bcornec** [comment]
No SElinux on Mageia neither by default, nor added afterwards

**Comment by xiaods** [comment]
```
/usr/lib64/golang/src/pkg/github.com/docker/libcontainer/namespaces/nsenter/nsenter.go:7: référence indéfinie vers « nsenter »
collect2: erreur: ld a retourné 1 code d'état d'exécution
````
it not english, i can't identify what happened. i only inpsect the nsenter have not correct runing. do you have some research on it?

**Comment by xiaods** [comment]
@bcornec my else two cents for your concern: because Go is cross language, you can build the libcontainer in ubuntu or fedora, then use the binary to Mageia. Because you choose the hard mode to find the way, i don't know what your real request, if you specially ask libcontainer to build successful on Mageia, please forget my words. thanks a lot.

**Comment by bcornec** [comment]
Hello, sorry for the frnech msg: In english it is:
/usr/lib64/golang/src/pkg/github.com/docker/libcontainer/namespaces/nsenter/nsenter.go:7: undefined reference to « nsenter » (coming from ld through collect2)

And I want to build it in my environment because I try to add Docker support to the Mageia Distribution (RPM based) and I'm trying to package it as well as libcontainer and I'm encoutering some issues. I don't want to pretend it's not linked to my environment, but googling about that error msg didn't lead to any useful result up to now.

**Comment by LK4D4** [comment]
nsenter little changed now
@bcornec If you still experiencing problems - feel free to open new issue.
