### ISSUE TITLE
Potential race condition in exec

### ISSUE THREAD

**Issue by kenshin54** [docker/libcontainer#368]
In CentOS 6.5, I created a new process by `docker exec`, but the cgroups of new process are incorrect. After debugging, I found a potential race condition between `EnterCgroups` and `nsenter-exec`.

https://github.com/docker/libcontainer/blob/master/namespaces/execin.go#L60-L76
https://github.com/docker/libcontainer/blob/master/namespaces/nsenter/nsenter.c#L174-L244

`ExecIn` will start the `nsenter-exec` first, then let the process enter the conainer's cgroups. And `nsenter` will join the namespaces of init process, then fork the new process. If the code of `nsenter` is executed before `EnterCgroups`, the cgroups of new process may not be fully attached.

I'm not sure is my point correct or not, maybe someone can help me reviewing this issue.

Thanks!

**Comment by dqminh** [comment]
Which version of docker did you test this on ? If i remember correctly, docker 1.4.1 should include the fix for this (https://github.com/docker/libcontainer/pull/336), which blocks the user process from spawning until the cgroups are setup.

**Comment by kenshin54** [comment]
@dqminh Thanks for response. It seems docker didn't merge this fix in the v1.4.1, but it has been merged in 1.5.0.

https://github.com/docker/docker/blob/v1.4.1/vendor/src/github.com/docker/libcontainer/namespaces/nsenter/nsenter.c
https://github.com/docker/docker/blob/v1.5.0/vendor/src/github.com/docker/libcontainer/namespaces/nsenter/nsenter.c
