### ISSUE TITLE
What do you think about adding two call backs to libcontainer

### ISSUE THREAD

**Issue by rhatdan** [docker/libcontainer#380]
This goes back to the tmpfs patches I have been trying to get through, where I want to grab the content off of the underlying file system and put it on the new tmpfs file system.

I was thinking of a call back like premount/postmount  callbacks, perhaps where premount returns a 
reference which is passed to postmount.

Then we could back up the contents of the mount on directory to memory and untar the memory on to the new tmpfs in postmount.

**Comment by crosbymichael** [comment]
I'm +1 on hooks that shell out to specified scripts.  Should something like that work or what type of callbacks were you thinking about?

**Comment by rjnagal** [comment]
pre-mount and post-mount hooks would encourage hooks after every ns setup. @rhatdan  Would it be enough to have a pre-setup and post-setup hook and not tie it to a specific ns setup?

Ideally, we would also need destroy hooks to clean the setup that is not automatically cleared by ns destruction.

**Comment by rhatdan** [comment]
Well the hooks I am looking for here are not for NS setup, but more for mounting each file system within the mnt namespace.   Since all of the namespaces are usually handled within a single clone. I am not sure what a Pre Namespace would do for you.  I guess a post namespace might be handy.

Google was looking for something a little more elaborate, where they would like to examine the content of the mnt namespace after PID 1 has stopped running.  But I think that is beyond the scope of this issue.

**Comment by dqminh** [comment]
i'm +1 for adding hooks to external scripts too. It can be helpful in many cases for example, manipulating the rootfs directory ( backup / mount tmpfs / mount ecryptfs ) before the container is running.

fwiw, here's the existing hook structure for lxc http://man7.org/linux/man-pages/man5/lxc.container.conf.5.html. It has two specific hooks for mount namespace ( and a few more ), `pre-mount` where namespace is setup but pivot root is not run, and `mount` after pivot root is finished.

**Comment by rhatdan** [comment]
So in PR#11254 we took a stab at using channels and callbacks for implementation of PreMount/PostMount hooks.   Both failed, because of the way docker and libcontainer communicate.  We would like to move this forward, and were wondering if people had other ideas with some concrete examples of how it could be done.

**Comment by LK4D4** [comment]
We discussed in #docker-dev `map[string]exec.Cmd`, where key defines place of call `exec.Cmd`, we can pass whole container config or its parts to such `cmds` as env.

**Comment by mrunalp** [comment]
https://github.com/docker/libcontainer/pull/495

**Comment by LK4D4** [comment]
#495 was merged
