### ISSUE TITLE
Would a customer expect --ipc=host to also share /dev/shm with the host?

### ISSUE THREAD

**Issue by rhatdan** [docker/libcontainer#413]
A lot of IPC tools use /dev/shm for IPC, and I have been asked if we should make a change to automatically bind mount /dev/shm from the host into the container.

Thoughts?

**Comment by rjnagal** [comment]
I think @mrunalp proposed having a tmpfs backed /dev/shm for each ipc namespace, which provides the same semantics.

**Comment by rhatdan** [comment]
I probably talked to him about it while I was at the DGAB.  I just wanted to open the issue.  I remembered it when I was looking at the ability to expand the size of /dev/shm within the container.

**Comment by avagin** [comment]
As far as I know /dev/shm isn't a part of ipc namespace in a kernel, so I think we don't need to do this automatically in libcontainer. Docker can add this bind-mount in a container config if it's required.

**Comment by rhatdan** [comment]
Yes I understand this. Just wanted to discuss if this is a usability issue.  Should we make it automatic?

Is there even a way to do something where /dev/shm is shared between multiple containers and not shared with the host?

**Comment by mrunalp** [comment]
@avagin Yeah, that's exactly what I had in mind. 
@rhatdan Not sure about it should be automatic. Maybe propose an issue and docker to see what people feel. If docker doesn't like the idea, then it is simple enough to do it from higher orchestration.
Only thing we need to make sure is that container /dev/shm mount doesn't override the bind mount as it does today.

**Comment by LK4D4** [comment]
@mrunalp Do you know what's status here? :)

**Comment by mrunalp** [comment]
@LK4D4 It is here https://github.com/docker/docker/pull/12159. I think we can close this issue and track it on that PR.

**Comment by LK4D4** [comment]
@mrunalp Thanks.
Closing.
