### ISSUE TITLE
selinux: Getfilecon returns a 0 byte at the end

### ISSUE THREAD

**Issue by mrunalp** [docker/libcontainer#440]
@rhatdan We are seeing an extra byte when calling selinux.Getfilecon and I see that it is returned from the getxattr system call itself. Should we be taking out that byte in selinux.Getfilecon function?

See -- https://gist.github.com/mrunalp/b67d63290651c69b0a3a

**Comment by rhatdan** [comment]
@eparis Do you remember if xatts store an extra byte in the file system.

Here is the code in C.

int getfilecon_raw(const char *path, char ** context)
{
	char *buf;
	ssize_t size;
	ssize_t ret;

	size = INITCONTEXTLEN + 1;
	buf = malloc(size);
	if (!buf)
		return -1;
	memset(buf, 0, size);

	ret = getxattr(path, XATTR_NAME_SELINUX, buf, size - 1);
	if (ret < 0 && errno == ERANGE) {
		char *newbuf;

		size = getxattr(path, XATTR_NAME_SELINUX, NULL, 0);
		if (size < 0)
			goto out;

		size++;
		newbuf = realloc(buf, size);
		if (!newbuf)
			goto out;

		buf = newbuf;
		memset(buf, 0, size);
		ret = getxattr(path, XATTR_NAME_SELINUX, buf, size - 1);
	}
      out:
	if (ret == 0) {
		/* Re-map empty attribute values to errors. */
		errno = ENOTSUP;
		ret = -1;
	}
	if (ret < 0)
		free(buf);
	else
		*context = buf;
	return ret;
}

**Comment by eparis** [comment]
SELinux, being C based, includes nul terminators.  Golang does not appear to write the nul terminator into the xattr.

In the selinux function: setfilecon_raw()
        int rc = setxattr(path, XATTR_NAME_SELINUX, context, strlen(context) + 1,

So we write the nul into the kernel (and thus get it back out)

**Comment by eparis** [comment]
@mrunalp so yes, the golang code should probably check to make sure the last thing is a nul and remove it...

**Comment by mrunalp** [comment]
@rhatdan @eparis Thanks. We can add that check to libcontainer.

**Comment by mrunalp** [comment]
Closed by #443
