### ISSUE TITLE
cap_last_cap not present on rhel6

### ISSUE THREAD

**Issue by vbatts** [docker/libcontainer#452]
pulling in https://github.com/syndtr/gocapability/pull/4 has caused docker to be able to launch containers on rhel6

```
vbatts@bananaboat ~ (master *) $ /home/vbatts/src/docker/docker/bundles/1.5.0-dev/dynbinary/docker-1.5.0-dev -H tcp://127.0.0.1:6666 run -it busybox top
FATA[0002] Error response from daemon: Cannot start container af71a89ee9308348c36108f325c006834243401a4b2cc6851bb147170b80bf80: [8] System error: open /proc/sys/kernel/cap_last_cap: no such file or directory
```

**Comment by vbatts** [comment]
i've opened a request for this to be backported as well https://bugzilla.redhat.com/show_bug.cgi?id=1202508

**Comment by crosbymichael** [comment]
`You are not authorized to access bug #1202508. To see this bug, you must first log in to an account with the appropriate permissions.`

**Comment by donhcd** [comment]
is this resolved by #478 ?

**Comment by LK4D4** [comment]
@donhcd Yes, it was. Thank you!

**Comment by vbatts** [comment]
will this be pulled in by a bump of libcontainer in docker? or will it need
a bump of gocapability in docker too?

On Tue, Mar 24, 2015 at 2:06 PM, Alexander Morozov <notifications@github.com

**Comment by LK4D4** [comment]
@vbatts Yup it will be, maybe today if there wasn't another fixes to libcontainer.

**Comment by vbatts** [comment]
thanks

On Tue, Mar 24, 2015 at 2:11 PM, Alexander Morozov <notifications@github.com
