### ISSUE TITLE
Add basic documentation to the nsinit directory to spawn containers

### ISSUE THREAD

**Issue by crosbymichael** [docker/libcontainer#468]
**Problem**
nsinit lacks basic getting started documentation.

**Solution**

Add basic documentation to the `nsinit` directory that explains how to get a simple busybox container up and running and the available options that one can pass.

**Comment by resouer** [comment]
#dibs We're writing a PR to improve the doc.

**Comment by crosbymichael** [comment]
@resouer thanks!!!

**Comment by wonderflow** [comment]
@crosbymichael I have a problem to understand how the nsinit  read the configration file.

I didn't find any code in libcontainer or nsinit that have loaded the "container.json" file.

The whole libcontainer project is searched and only find "container.json" was reminded in README and Dockerfile.

So I hope you can do me a favor to tell where do the nsinit load the "container.json" into "cli context".

Thank you very much.

**Comment by hqhq** [comment]
@wonderflow the config file should be passed through `--config`, `nsinit exec` will parse and load it,  your command from `README.md`, `container.json` won't be available, nsinit would get config from function `getTemplate()`.
https://github.com/docker/libcontainer/pull/493 is fixing the doc.

**Comment by wonderflow** [comment]
@hqhq Thanks for your explanation.

**Comment by wonderflow** [comment]
@crosbymichael 
Another question is what is "nsinit init" used for?
I've also ask the question [here](https://groups.google.com/forum/#!topic/docker-dev/ocnSQtQmZmQ).
Hope to get some help, Thanks!
