### ISSUE TITLE
can not build on Mac OSX

### ISSUE THREAD

**Issue by tonicbupt** [docker/libcontainer#470]
When I tried my project that uses libcontainer (which I haven't updated libcontainer for long... ), these errors showed up. On `darwin/amd64`, `syscall` doesn't have these constants defined... So I am wondering if `namespace.go` will be differed by platform.

```
$ go build
# github.com/docker/libcontainer/configs
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:90: undefined: syscall.CLONE_NEWNET
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:91: undefined: syscall.CLONE_NEWNS
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:92: undefined: syscall.CLONE_NEWUSER
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:93: undefined: syscall.CLONE_NEWIPC
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:94: undefined: syscall.CLONE_NEWUTS
../../.go/src/github.com/docker/libcontainer/configs/namespaces.go:95: undefined: syscall.CLONE_NEWPID
```

**Comment by mrunalp** [comment]
@tonicbupt These flags are Linux specific. Someone would have to implement the new libcontainer API using the facilities (if any) provided by Mac OS X do the namespacing for it to work natively.

**Comment by mrunalp** [comment]
Closing this until someone adds Mac OS support :)
