### ISSUE TITLE
Allow POSIX IPC sharing between docker containers

### ISSUE THREAD

**Issue by lhuard1A** [docker/libcontainer#471]
Linux provides two IPC APIs: the SysV one and the POSIX one.

1. The SysV IPC objects (managed with `shmget`, `msgget`, `semget`, etc.), are implemented as kernel objects inside the IPC namespace.
Docker containers can already share the IPC namespace between them or with the host thanks to the `--ipc=container:xxx` resp. `--ipc=host` parameters.

2. The POSIX IPC objects (managed with `shm_open`, `mq_open`, etc.) are implemented with dedicated filesystems (shared memory use a `tmpfs` mounted in `/dev/shm` and message queues use a `mqueue` fs mounted in `/dev/mqueue`)
Docker containers have these filesystems but Docker doesn’t provide any facility to share them. (docker/libcontainer#413 mention it)

Would it be possible to implement POSIX IPC sharing feature inside docker?

### UX

From a technical point of view, there is no link between IPC namespace and mounted fs, so, we could have:
* `--sysvipc=host`, `--sysvipc=container:xxx` for sharing the IPC namespace with the host resp. between containers
* `--posixshm=host`, `--posixshm=container:xxx` for sharing `/dev/shm` with the host resp. between containers
* `--posixmqueue=host`, `--posixmqueue=container:xxx` for sharing `/dev/mqueue` with the host resp. between containers

From a user point of view I may not need so fine grained parameters, so we could have:
* `--posixipc=` that sets both `--posixshm` and `--posixmqueue`
* `--ipc=` that sets both `--sysvipc` and `--posixipc`

### Implementation

In practice, we could have the the `tmpfs` for shared memory and the `mqueue` filesystems mounted on the host and have them bind-mounted inside the appropriate containers exactly like what we have for volumes today.

**Comment by mrunalp** [comment]
@lhuard1A You probably want to open a docker issue for this feature.

**Comment by mrunalp** [comment]
See https://github.com/docker/docker/issues/12046
