### ISSUE TITLE
xattr: drops the C \0 byte when reading some selinux attributes #436

### ISSUE THREAD

**Issue by pmorie** [docker/libcontainer#499]
Forked from #436; needs investigation.

**Comment by timothysc** [comment]
hit *this on k8's e2e secrets test.

**Comment by pmorie** [comment]
Looks like @mrunalp fixed it: https://github.com/docker/libcontainer/commit/a9442e6660e71fd2058310e6155de3ef5e4f5fdf

**Comment by pmorie** [comment]
Closing
