### ISSUE TITLE
Please add support for stable OpenVZ version (2.6.32) to libcontainer

### ISSUE THREAD

**Issue by pavel-odintsov** [docker/libcontainer#52]
Hello!

We very interesting in this feature. Could you add it? We can participate in development but need some help from Parallels team because OpenVZ interfaces is not documented fully.

**Comment by LK4D4** [comment]
There is already PR for merging `libct` support. I think that libct will work on `openvz`.

**Comment by pavel-odintsov** [comment]
Are you sure? I do not know about support of OpenVZ from libct side. Xemul, could you help us?

**Comment by xemul** [comment]
Sure. We had the openvz "backend" in libct on the early stages, then @avagin concentrated on fixing issues to have the libct core merged. Once this is done we will resurrect the openvz backend.  I guess @mrunalp and @crosbymichael can tell us about their plans about merging it in (pr #434 ).

**Comment by mrunalp** [comment]
I know that @avagin did some fixes last week and I need to retry it again on Fedora. I should be test them tomorrow and report here.

**Comment by xemul** [comment]
Awesome :) Thanks!
