### ISSUE TITLE
Restore failed for a criu checkpointed container with nsinit

### ISSUE THREAD

**Issue by huikang** [docker/libcontainer#522]
Hi, 
I tested the criu branch of libcontainer. After checkpointing a container with "nsinit --criu checkpoint", the restore process failed and the restore.log shows that
    
    # nsinit-criu --criu /usr/local/sbin/criu restore

(00.009942)      1: Path `/root/rootfs' resolved to `./' mountpoint
(00.009949)      1: Error (mount.c:2172): New root and old root are the same
(00.035408) Error (cr-restore.c:1867): Restoring FAILED.

I fixed the problem with
    $ mount --rbind /root/rootfs /root/rootfs

Then the the process can be restored in the container namespace
    # nsinit --criu /usr/local/sbin/criu restore
    # INFO[0000] Restored

Is there anything wrong with the mount or the current restore implementation? Thanks.

- Hui

Linux docker-102 3.18.8 #3 SMP Wed Mar 18 16:19:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Storage Driver: devicemapper 
nsinit version 2

**Comment by avagin** [comment]
@huikang, could you try out https://github.com/docker/libcontainer/pull/534

**Comment by huikang** [comment]
The patch solved the problem. Thanks.

- Hui

**Comment by boucher** [comment]
Should we close this issue?
