### ISSUE TITLE
Is there any known work for using libcontainer outside docker

### ISSUE THREAD

**Issue by sainath14** [docker/libcontainer#563]
Hello all,
 I am looking for any work that uses libcontainer outside of docker. If there is any, please let me know.

 I am new to libcontainer and also go language, how can I debug/reverse engineer libcontainer apis. Any help is greatly appreciated.

**Comment by crosbymichael** [comment]
You can find a small binary called `nsinit` in libcontainer with the implementation in a simple go tool

https://github.com/docker/libcontainer/blob/master/nsinit/exec.go#L35

**Comment by LK4D4** [comment]
I'm closing this issue, becaue it's not really issue :)
