### ISSUE TITLE
Too many files in root directory

### ISSUE THREAD

**Issue by hqhq** [docker/libcontainer#571]
Maybe we can move all `libcontainer` package files into a dir named `libcontainer`? Like Docker has a dir named Docker which contains main package files. WDYT?

**Comment by crosbymichael** [comment]
I kinda like the root dir because its simple, there is only one place to look to find out where the code is.

**Comment by hqhq** [comment]
Thanks for answering, just make sure you noticed this issue, anyway it's your call, let's leave it as it was.
