### ISSUE TITLE
can not close a namespace

### ISSUE THREAD

**Issue by CMGS** [docker/libcontainer#593]
I wrote some code to add macvlan device to a container, however, it can not get out from container's namespace. 

here is the code https://gist.github.com/CMGS/4f60fd8da2014eed0dd8

Is there anyone can help me to solve this problem?

this is output
```
root@kili1:/home/armin# ./test
ifc in host &{2119 1500 mt2 16:2c:ef:fe:09:44 broadcast|multicast}
set ip &{2119 1500 mt2 16:2c:ef:fe:09:44 broadcast|multicast} <nil>
up link &{2119 1500 mt2 16:2c:ef:fe:09:44 broadcast|multicast} <nil>
close <nil>
check outside &{2119 1500 mt2 16:2c:ef:fe:09:44 up|broadcast|multicast}
```

**Comment by LK4D4** [comment]
@CMGS You need to `Setns` back in parent namespace. You can find such code here: https://github.com/docker/libnetwork/blob/master/sandbox/namespace_linux.go
