### ISSUE TITLE
Selinux context returned be selinux.Getfilecon is sometimes incorrectly truncated

### ISSUE THREAD

**Issue by pmorie** [docker/libcontainer#598]
Found during research into https://github.com/GoogleCloudPlatform/kubernetes/issues/8499

The selinux context returned by `Getfilecon` is sometimes incorrectly truncated.  Previously, we filed an issue, #499 to truncate the extra byte that was sometimes present on the selinux xattrs inspected by this func.  Now, it appears as though the value is incorrectly truncated.

cc @timothysc @mrunalp

**Comment by timothysc** [comment]
mounting tmpfs for volume test-volume with opts rootcontext="system_u:object_r:var_lib_t:s"

drwxr-xr-x. root root system_u:object_r:var_lib_t:s0   kubelet

**Comment by mrunalp** [comment]
Hmm, I think probably the null check is incorrect hence 0 is being mistaken for the null byte. I am looking into it.

**Comment by mrunalp** [comment]
What linux distribution are the tests running on?
I tried something on F21 and file labels under /var/lib are getting returned correctly.

**Comment by timothysc** [comment]
@mrunalp Atomic 7.1.2

**Comment by mrunalp** [comment]
@timothysc Could we get the output of
strace getfattr -n security.selinux kubelet 2>&1 | grep getxattr?

I want to check if the value has been written with a trailing \0 or not.

**Comment by timothysc** [comment]
@mrunalp no dice on atomic.  When I try the tools container, it does not contain attr. 

@jeremyeder ^

**Comment by jeremyeder** [comment]
Hey you should have access to yum to do a yum install of attr or any other tool you need.

**Comment by eparis** [comment]
getxattr("/host/var/lib/kubelet", "security.selinux", "system_u:object_r:var_lib_t:s0", 256) = 31

**Comment by eparis** [comment]
Or in hex, just for funzies

getxattr("\x2f\x68\x6f\x73\x74\x2f\x76\x61\x72\x2f\x6c\x69\x62\x2f\x6b\x75\x62\x65\x6c\x65\x74", "\x73\x65\x63\x75\x72\x69\x74\x79\x2e\x73\x65\x6c\x69\x6e\x75\x78", "\x73\x79\x73\x74\x65\x6d\x5f\x75\x3a\x6f\x62\x6a\x65\x63\x74\x5f\x72\x3a\x76\x61\x72\x5f\x6c\x69\x62\x5f\x74\x3a\x73\x30", 256) = 31

**Comment by eparis** [comment]
\x30 == '0'

So there appears to be no trailing nil.  Still not sure why libcontainer would be stripping anything...

**Comment by mrunalp** [comment]
Yeah, not clear to me either.
Could you try running this program on the file?

```go
package main

import (
        "fmt"
        "log"
        "os"

        "github.com/docker/libcontainer/selinux"
)

func main() {
        if len(os.Args) < 2 {
                log.Fatalf("Usage: selinuxtest /pat/to/file")
        }
        con, err := selinux.Getfilecon(os.Args[1])
        if err != nil {
                log.Fatalf("Failed to get selinux context: %v", err)
        }
        fmt.Println(con)
}
```

**Comment by eparis** [comment]
./test /var/lib/kubelet/
system_u:object_r:var_lib_t:s0

**Comment by mrunalp** [comment]
That looks like it is working correctly.

**Comment by pmorie** [comment]
Looks to me too, but we're still trying to nail down on whether this is being tested on the exact same hash as @timothysc hit it with

**Comment by mrunalp** [comment]
@pmorie okay, yeah makes sense to track that down.

**Comment by timothysc** [comment]
This may be a re-hash of a previous issue we had fixed a while back due to a failed upgrade- https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2015-May/msg00117.html

**Comment by timothysc** [comment]
I think we can close this one, but we likely need to open a different one from the other issue.

**Comment by eparis** [comment]
"the other" meaning /etc on NFS doesn't work for systemd units?  maybe, but I don't think you get to blame kube or libcontainer for that one   :)

**Comment by timothysc** [comment]
lol.

**Comment by mrunalp** [comment]
Closing this for now.
