### ISSUE TITLE
Restoring a container doesn't initialize it if it hasn't already been initialized

### ISSUE THREAD

**Issue by boucher** [docker/libcontainer#612]
When a container gets started, it creates a parent init process, which eventually calls StartInitialization and sets up a bunch of things inside the container. But restoring into a new container created but never previously started doesn't seem to ever go through this process, which means that in some circumstances the restore will fail (specifically, if it's mounting a directory, but possibly others too).

This used to work at some point, but I haven't yet tracked down exactly when it stopped. @avagin do you have any ideas here? Could we check the container's state, and if it isn't already checkpointed, perhaps run the CriuSwk process through a parent process that first calls the initialization code?

**Comment by boucher** [comment]
Adding this in Restore() right before calling criuSwrk seems to resolve the issue:

```go
+
+       status, err := c.currentStatus()
+       if err != nil {
+               return err
+       }
+
+       if status != Checkpointed {
+               parent, err := c.newParentProcess(process, true)
+               if err != nil {
+                       return newSystemError(err)
+               }
+               if err := parent.start(); err != nil {
+                       // terminate the process to ensure that it properly is reaped.
+                       if err := parent.terminate(); err != nil {
+                               logrus.Warn(err)
+                       }
+                       return newSystemError(err)
+               }
+               process.ops = parent
+       }
+
```

**Comment by boucher** [comment]
Looking closer, I actually just end with two processes doing this.

**Comment by avagin** [comment]
The file tree should not be changed between dump and restore. When you create a new container, directories for bind-mounts may be absent and they will be created on the first start. But "criu restore" expects that they are there and fails if they are not.
https://github.com/docker/libcontainer/blob/master/rootfs_linux.go#L151

**Comment by boucher** [comment]
Sure, but there's no reason they can't be bind-mounted before restoring. I make a docker commit after checkpointing, and create a new container with the new fs image, so the fs is already the same -- and since my bind mount is read only, that is also the same. But because we aren't initing the bind mounts, it fails.

**Comment by avagin** [comment]
@boucher I've compiled docker from your repo (cr-combined), but I can't reproduce this issue. Could you look at my sequence of actions and find what you do differently?
https://asciinema.org/a/6cfv5n4a57s74igagmdrs0x6s
