### ISSUE TITLE
Remove dep on dotcloud/docker/pkg/symlink

### ISSUE THREAD

**Issue by crosbymichael** [docker/libcontainer#96]
I'm pretty sure that this functionality should not exist in libcontainer but we will have to be careful about regressions if we try to remove this altogether.  If not we will have to port over this code.  It is pretty complicated and is used in other places within docker so it should be shared and not duplicated.

```
mount/init.go:
13:     "github.com/dotcloud/docker/pkg/symlink"
```

**Comment by xiaods** [comment]
@crosbymichael does it should be close this issue?
